# Generated by Django 3.1.4 on 2020-12-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Oprations_tutorial',
        ),
    ]
